include:
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    snippet: studio-rpc-usb-uart
    artifact-name: nice_sofle_left_oled
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    artifact-name: nice_sofle_right_oled
  - board: nice_nano_v2
    shield: settings_reset
